version: "3"
services:
  mysql:
    build: ./mysql/
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d #初期処理のフォルダ。初回起動のみでおｋ
      - ./mysql/db:/var/lib/mysql #ここにデータ永続化するためのファイルが入る。
    image: mysql_app
    container_name: "mysql_run"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - '3306:3306'
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true